### ISSUE TITLE
Built-in pip of python3.12 in all is broken

### ISSUE THREAD

**Issue by hxyannay** [snakepacker/python#13]
Seems like the built-in pip of python3.12 in the all image is broken:
```
docker run --rm -it snakepacker/python:all python3.12 -m pip
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/exceptions.py", line 7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

I assume that it happens due to the installation of pip with version 21.2.4 in the [all](https://github.com/snakepacker/python/blob/master/all/Dockerfile) Dockerfile.
In order to fix it I would suggest updating the versions of pip, setuptools, wheel, cython and others to the latest version, or rather not lock them at all so that newer versions will work without any need to change again.

Would be happy to open a PR myself if you choose which of the options is better (locking to newer versions or removing the lock altogether)

**Comment by mosquito** [comment]
Hi @hxyannay, I happen to have some time on my hands and pip 24.0 was released a few hours ago, so I took things into my own hands and decided to check it out.
If you have any comments, feel free to offer them in the PR. I'd also be happy if you check it out from my branch in your cases. My quick tests showed that everything is perfectly fine.
